#!/bin/sh -ex
echo "Instalando pihole..."
export PIHOLE_INTERFACE=eth0
export IPV4_ADDRESS=0.0.0.0
export IPV6_ADDRESS=0:0:0:0:0:0
export PIHOLE_DNS_1=8.8.8.8
export QUERY_LOGGING=true
export INSTALL_WEB_SERVER=true
export INSTALL_WEB_INTERFACE=true
export LIGHTTPD_ENABLED=true
export PIHOLE_SKIP_OS_CHECK=true

cp /usr/local/src/Pi-hole/automated\ install/basic-install.sh .
chmod +x ./basic-install.sh
bash -sex ./basic-install.sh --unattended
